---
on: [push, pull_request]
name: CI

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - uses: hecrj/setup-rust-action@v1

      - name: Launch the postgres and min.io images
        run: |
          cp .env.sample .env
          . .env
          mkdir -p ${CRATESFYI_PREFIX}/public-html
          docker-compose up -d db s3
          # Give the database enough time to start up
          sleep 5
          # Make sure the database is actually working
          psql "${CRATESFYI_DATABASE_URL}"

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --locked -- -D warnings

      - name: Build docs.rs
        run: cargo build --locked

      - name: Test docs.rs
        run: cargo test --locked -- --test-threads=1

      - name: Clean up the database
        run: docker-compose down --volumes

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Build the Docker image
        run: docker build -t docs-rs -f dockerfiles/Dockerfile .

      - name: Upload the Docker image to ECR
        uses: rust-lang/simpleinfra/github-actions/upload-docker-image@master
        with:
          image: docs-rs
          repository: staging-docs-rs
          region: us-west-1
          aws_access_key_id: "${{ secrets.aws_access_key_id }}"
          aws_secret_access_key: "${{ secrets.aws_secret_access_key }}"
        if: github.ref == 'refs/heads/master'
